bihe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("story.urls", namespace="story")),
    path("user/", include("useraccount.urls", namespace="user")),
    path("inbox/", include("inbox.urls", namespace="inbox")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

useraccount/urls.py
from django.urls import path
from useraccount.views import user_login, user_logout, SignupView, profile_view, edit_profile_view, visit_profile, PassWordChange, search

app_name = "user"

urlpatterns = [
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("registration/", SignupView.as_view(), name="registration"),
    path("profile/<str:username>/", profile_view, name="profile"),
    path("visit-profile/<int:profileid>/", visit_profile, name="visit_profile"),
    path("edit_profile/<str:username>/", edit_profile_view, name="edit_profile"),
    path("password",PassWordChange.as_view(template_name="password_change_form.html"),name="password-change"),
    path("search/", search, name="search"),
]

useraccount/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.


class User(AbstractUser):
    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

class Gender(models.TextChoices):
    MALE = ("male", "MALE")
    FEMALE = ("female", "FEMALE")
    OTHER = ("other", "OTHER")


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=255, choices=Gender.choices, default=Gender.OTHER)
    contact = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    birth_date = models.DateField(null=True)
    avatar = models.ImageField(upload_to="Profile", blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    height = models.DecimalField(max_digits=50, decimal_places=1, blank=True, null=True)
    marital_status = models.CharField(max_length=255, blank=True, null=True)
    religion = models.CharField(max_length=255, blank=True, null=True)
    mother_tongue = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True) 
    bio = models.TextField(blank=True, null=True)
    hubby = models.CharField(max_length=255, blank=True, null=True)
    favourite_foods = models.CharField(max_length=255, blank=True, null=True)
    favourite_places = models.CharField(max_length=255, blank=True, null=True)
    

    def __str__(self):
        return str(self.user)

class Education(models.Model):
    college_name = models.CharField(max_length=255, blank=True, null=True)
    degree = models.CharField(max_length=255, blank=True, null=True)
    percentage = models.DecimalField(max_digits=50, decimal_places=2, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="educations", blank=True, null=True)

    def __str__(self):
        return str(self.id)


class Job(models.Model):
    company_name = models.CharField(max_length=255, blank=True, null=True)
    department = models.CharField(max_length=255, blank=True, null=True)
    salary = models.IntegerField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="jobs", blank=True, null=True)

    def __str__(self):
        return str(self.id)

useraccount/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django import forms
from useraccount.models import Profile, Education, Job

User = get_user_model()

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username","first_name", "last_name", "email", "password1", "password2", )

class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    class Meta:
        Model = User
        fields = ("old_password", "new_password1", "new_password2", )

class ProfileForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    college_name = forms.CharField()
    degree = forms.CharField()
    percentage = forms.CharField()
    company_name = forms.CharField()
    department = forms.CharField()
    salary = forms.CharField()
    class Meta:
        model = Profile
        fields = ("first_name", "last_name", "gender", "email", "contact", "address", "birth_date", "avatar","age", "height", "marital_status", "religion", "mother_tongue", "country", "bio", "hubby", "favourite_foods", "favourite_places")

class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = ("college_name", "degree", "percentage")

class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ("company_name", "department", "salary")

useraccount/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from useraccount.forms import SignupForm, ProfileForm, PasswordChangingForm
from django.urls import reverse_lazy
from useraccount.models import Profile, Education, Job
from django.contrib.auth.decorators import login_required
from django.db.models import Q


User = get_user_model()


def user_login(request):
    form = AuthenticationForm(request.POST or None)
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse("story:matches"))
        else:
            messages.add_message(request, messages.ERROR, "Invalid Username or Password")
            return HttpResponseRedirect(reverse("user:login"))

    return render(request, "login.html", {"form": form})

class UserLoginView(LoginView):
    template_name = "login.html"

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("user:login"))


class SignupView(CreateView):
    template_name = "registration.html"
    form_class = SignupForm
    model = User
    success_url = reverse_lazy("user:login")

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        Education.objects.create(user=user)
        Job.objects.create(user=user)
        return super().form_valid(form)


def get_success_url(self):
    messages.add_message(self.request, messages.INFO, "Your Account Registered Succesfully.")
    return str(self.success_url)

@login_required
def profile_view(request, username):
    user = get_object_or_404(User, username=username)
    profile=Profile.objects.filter(user=request.user)
    education = Education.objects.filter(user=request.user)
    job = Job.objects.filter(user=request.user)
    context = {
        'user': user,
        'profile': profile,
        'education': education,
        'job': job
    }
    
    if request.user.is_authenticated and request.user.username==username:
        return render(request, "profile.html", context)
    else:
        return HttpResponseRedirect(reverse("user:login"))
    
@login_required
def visit_profile(request, profileid):
    profile = Profile.objects.get(id=profileid)
    education = Education.objects.all()
    context = {
        "profile": profile,
        "education": education
    }
    return render(request, "visitprofile.html", context)
    

@login_required
def edit_profile_view(request, username):
    user = get_object_or_404(User, username=username)
    education = get_object_or_404(Education, user=request.user)
    job = get_object_or_404(Job, user=request.user)
    if request.user.is_authenticated and request.user.username==username:
        user=request.user
        initial_data = {"first_name": user.first_name, "last_name": user.last_name, "email": user.email, "college_name": education.college_name, "degree": education.degree, "percentage": education.percentage, "company_name": job.company_name, "department": job.department, "salary": job.salary,}
        form = ProfileForm(request.POST or None, request.FILES or None, instance=request.user.profile, initial=initial_data)
        if form.is_valid():
            obj=form.save(commit=False)
            user=request.user
            user.first_name=form.cleaned_data.get("first_name")
            user.last_name = form.cleaned_data.get("last_name")
            user.email = form.cleaned_data.get("email")
            education.college_name = form.cleaned_data.get("college_name")
            education.degree = form.cleaned_data.get("degree")
            education.percentage = form.cleaned_data.get("percentage")
            job.company_name = form.cleaned_data.get("company_name")
            job.department = form.cleaned_data.get("department")
            job.salary = form.cleaned_data.get("salary")
            user.save()
            education.save()
            job.save()
            obj.save()
            form.save()
            messages.add_message(request, messages.INFO, "Your Profile Updated Succesfully.")
            return HttpResponseRedirect(reverse("user:profile", args=(request.user.username, )))
    return render(request, "edit_profile.html", {"form": form})
 
class PassWordChange(PasswordChangeView):
    form_class = PasswordChangingForm
    success_url=reverse_lazy("user:login")
    def get_success_url(self):
        message = messages.add_message(self.request, messages.INFO, "Your Password Updated Succesfully.")
        message
        return str(self.success_url)
    
def search(request):
    searchdata = request.GET.get("search")
    user=User.objects.filter(Q(first_name__icontains=searchdata) | Q(last_name__icontains=searchdata)).exclude(id=request.user.id)
    context = {
        'user': user,
    }
    return render(request, "search.html", context)

useraccount/templates/edit_profile.html
{% extends "base.html" %}

{% block content %}
<div class="mt-5">
    <form method="post" action="{% url 'user:edit_profile' request.user.username %}" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        {{ eduform.as_p }}
        {{ jobform.as_p }}

    <input class = "btn btn-info" type = "submit" name="submit" value="Update" />

    </form>
    
</div>
{% endblock content %}

useraccount/templates/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="{% static 'login/css/style.css' %}">

	</head>
	<body class="img js-fullheight" style="background-image: url({% static 'navbar/images/wedding.jpg' %});">
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
		      	<h3 class="mb-4 text-center">Have an account?</h3>
                {% if messages %}
                    {% for message in messages %}
                        <div class="text text-danger">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
				{% if message %}
                    {% for m in message %}
                        <div class="alert alert-success">
                            {{ m }}
                        </div>
                    {% endfor %}
                {% endif %}

		      	<form method="post" action="" class="signin-form">
                    {% csrf_token %}
		      		<div class="form-group">
		      			<input type="text" class="form-control" name="username" placeholder="Username" required>
		      		</div>
	            <div class="form-group">
	              <input id="password-field" type="password" class="form-control" name="password" placeholder="Password" required>
	              <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
	            </div>
	            <div class="form-group">
	            	<button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
	            </div>
	            <div class="form-group d-md-flex">
	            	<div class="w-50">
		            	<label class="checkbox-wrap checkbox-primary">Remember Me
									  <input type="checkbox" checked>
									  <span class="checkmark"></span>
									</label>
								</div>
								<div class="w-50 text-md-right">
									<a href="#" style="color: #fff">Forgot Password</a>
								</div>
								
	            </div>
		
	          </form>
			  <a href="{% url 'user:registration' %}"><button class="btn btn-secondary">Register</button></a>
	          <p class="w-100 text-center">&mdash; Or Sign In With &mdash;</p>
	          <div class="social d-flex text-center">
	          	<a href="#" class="px-2 py-2 mr-md-1 rounded"><span class="ion-logo-facebook mr-2"></span> Facebook</a>
	          	<a href="#" class="px-2 py-2 ml-md-1 rounded"><span class="ion-logo-twitter mr-2"></span> Twitter</a>
	          </div>
		      </div>
				</div>
			</div>
		</div>
	</section>
  <script src="{% static 'login/js/jquery.min.js' %}"></script>
  <script src="{% static 'login/js/popper.js' %}"></script>
  <script src="{% static 'login/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'login/js/main.js' %}"></script>

	</body>
</html>

useraccount/templates/password_change_form.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Change Password</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href="{% static 'css/bs.min.css' %}" type="text/css" />

		<!-- MATERIAL DESIGN ICONIC FONT -->
		<link rel="stylesheet" href="{% static 'registration/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css' %}">
		
		<!-- STYLE CSS -->
		<link rel="stylesheet" href="{% static 'registration/css/style.css' %}">
	</head>

	<body>

		<div class="wrapper" style="background-image: url('images/bg-registration-form-2.jpg');">
			<div class="inner">
				<form method="post" action="">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="text text-danger">
                        {{ field.errors }}
                    </div>
                    {% endfor %}
					<h3>Change Password</h3>
                    <div class="form-wrapper">
							<label for="">Current Password</label>
							<input type="password" class="form-control" name="old_password">
						</div>
					<div class="form-wrapper">
						<label for="">New Password</label>
						<input type="password" class="form-control" name="new_password1">
					</div>
					<div class="form-wrapper">
						<label for="">Confirm New Password</label>
						<input type="password" class="form-control" name="new_password2">
					</div>
					<div class="">
					</div>
					<div class="form-group">
	            	<button id="btn" type="submit" class="btn btn-primary submit px-3">Done</button>
	            </div>
				</form>
			</div>
		</div>
		
	</body>
</html>

useraccount/templates/registration.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Registration</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href="{% static 'css/bs.min.css' %}" type="text/css" />

		<!-- MATERIAL DESIGN ICONIC FONT -->
		<link rel="stylesheet" href="{% static 'registration/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css' %}">
		
		<!-- STYLE CSS -->
		<link rel="stylesheet" href="{% static 'registration/css/style.css' %}">
	</head>

	<body>

		<div class="wrapper" style="background-image: url('images/bg-registration-form-2.jpg');">
			<div class="inner">
				<form method="post" action="">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="text text-danger">
                        {{ field.errors }}
                    </div>
                    {% endfor %}
					<h3>Registration Form</h3>
					<div class="form-group">
						<div class="form-wrapper">
							<label for="">First Name</label>
							<input type="text" class="form-control" name="first_name">
						</div>
						<div class="form-wrapper">
							<label for="">Last Name</label>
							<input type="text" class="form-control" name="last_name">
						</div>
					</div>
					<div class="form-wrapper">
						<label for="">Email</label>
						<input type="text" class="form-control" name="email">
					</div>
                    <div class="form-wrapper">
							<label for="">Username</label>
							<input type="text" class="form-control" name="username">
						</div>
					<div class="form-wrapper">
						<label for="">Password</label>
						<input type="password" class="form-control" name="password1">
					</div>
					<div class="form-wrapper">
						<label for="">Confirm Password</label>
						<input type="password" class="form-control" name="password2">
					</div>
					<div class="checkbox">
						<label>
							<input type="checkbox" id="check" onclick="enable()"> I caccept the Terms of Use & Privacy Policy.
							<span class="checkmark"></span>
						</label>
					</div>
					<div class="form-group">
	            	<button disabled="true" id="btn" type="submit" class="btn btn-primary submit px-3">Register</button>
	            </div>
				</form>
			</div>
		</div>
		
	</body>
    <script>
    function enable() {
        var check = document.getElementById("check");
        var btn = document.getElementById("btn");
        if (check.checked) {
            btn.removeAttribute("disabled");
        }  else {
            btn.disabled = "true";
        }

    }
    </script>
</html>

useraccount/templates/search.html
{% extends 'base.html' %}
{% block content %}
{% for u in user %}
<div class="container emp-profile mt-5">
            <form method="get">
                <div class="row">
                    <div class="col-sm-12 col-md-3 col-lg-3">
                        <div class="profile-img">
                        <style>
                            .thumbnail {
                                width: 200px;
                                height: 200px;
                                border: none;
                                border-radius: 100px;
                            }                        
                        </style>
                        {% if u.profile.avatar %}
                            <img class="thumbnail" src="{{ u.profile.avatar.url }}" alt=""/>
                        {% endif %}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                {% if messages %}
                                    {% for message in messages %}
                                        <div class="alert alert-success">
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}

                                        {{ u.first_name }} {{ u.last_name }}
                                    </h5>
                                    <h6>
                                    </h6>
                                    <p class="proile-rating"><span></span></p>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                            </ul>  
                        
                        </div>
                    </div>
                    <div class="col-md-2">
                    <a href="{% url 'user:visit_profile' u.profile.id %}" class="editbtn" role="button">Visit Profile</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Username</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ u.username }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Name</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ u.first_name }} {{ u.last_name }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Gender</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ u.profile.gender }}</p>
                                                
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ u.email }}</p>
                                            </div>
                                        </div>
                                        
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Contact</label>
                                            </div>
                                            
                                            <div class="col-md-6">
                                                <p>{{ u.profile.contact }}</p>
                                            
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Address</label>
                                            </div>
                                            <div class="col-md-6">
                                                
                                                <p>{{ u.profile.address }}</p>
                                                
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Hubby</label>
                                            </div>
                                            <div class="col-md-6">
                                                
                                                <p>{{ u.profile.hubby }}</p>
                                                
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Favourite Foods</label>
                                            </div>
                                            <div class="col-md-6">
                                                
                                                <p>{{ u.profile.favourite_foods }}</p>
                                                
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Favoruite Places</label>
                                            </div>
                                            <div class="col-md-6">
                                                
                                                <p>{{ u.profile.favourite_places }}</p>
                                                
                                            </div>
                                        </div>
                            
                            
                                        <style>
                                    table.customTable {
                                    width: 100%;
                                    border-collapse: collapse;
                                    border-width: 2px;
                                    border-color: lightgrey;
                                    border-style: solid;
                                    color: #000000;
                                
                                    }

                                    table.customTable td, table.customTable th {
                                    border-width: 2px;
                                    border-color: grey;
                                    border: None;
                                    border-style: ;
                                    padding: 5px;
                                    }

                                    table.customTable thead {
                                    background-color: lightgrey;
                                    }
                                    </style>

                                    <table class="customTable">
                                    <thead>
                                        <tr>
                                        <th>College Name</th>
                                        <th>Degree</th>
                                        <th>Percentage</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                            {% for education in u.profile.educations.all %}
                                        <tr>
                                        <td>{{ education.college_name }}</td>
                                        <td>{{ education.degree}}</td>
                                        <td>{{ education.percentage }}</td>
                                        </tr>
                                            {% endfor %}
                                    </tbody>
                                    </table>

                                    <table class="customTable mt-4">
                                    <thead>
                                        <tr>
                                        <th>Company Name</th>
                                        <th>Department</th>
                                        <th>Salary</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                            {% for job in u.profile.jobs.all %}
                                    
                                        <tr>
                                        <td>{{ job.company_name }}</td>
                                        <td>{{ job.department }}</td>
                                        <td>{{ job.salary }}</td>
                                        </tr>
                                            {% endfor %}
                                    </tbody>
                                    </table>

                            
                            </div>

                        </div>
                    </div>
                </div>
            </form>          
        {% endfor %}
{% endblock content %}