bihe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("story.urls", namespace="story")),
    path("user/", include("useraccount.urls", namespace="user")),
    path("inbox/", include("inbox.urls", namespace="inbox")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inbox/urls.py
from django.urls import path
from inbox.views import message_view, message_to_user, delete_message
app_name="inbox"

urlpatterns = [
    path("messages/", message_view, name="messages"),
    path("messages/<str:username>/", message_to_user, name="message_user"),
    path("delete-message/", delete_message, name="delete_message"),
]

inbox/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Message(TimeStampModel):
    description = models.TextField()
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sent_messages")
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="received_messages")
    

inbox/forms.py
from django import forms
from inbox.models import Message

class InboxForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("description", )

inbox/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model
from inbox.models import Message
from inbox.forms import InboxForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


User = get_user_model()


def message_view(request):
    users = User.objects.filter().exclude(id=request.user.id)
    context = {"users": users}
    return render(request, "message.html", context)


def message_to_user(request, username):
    users = User.objects.filter().exclude(id=request.user.id)
    to_user = User.objects.get(username=username)
    messages = Message.objects.filter(
        from_user__in=[request.user, to_user],
        to_user__in=[request.user, to_user],
    ).order_by("created_at")
    form = InboxForm(request.POST or None)
    if form.is_valid():
        message = form.save(commit=False)
        message.from_user = request.user
        
        message.to_user = to_user
        message.save()
        return HttpResponseRedirect(reverse("inbox:message_user", args=(username, )))
    context = {"conversations": messages, "form": form, "users": users, "username": username , "to_user": to_user}
    return render(request, "message.html", context)

@login_required
def delete_message(request):
    messageid = request.POST.get("messageid")
    chat = get_object_or_404(Message, id=messageid, from_user=request.user)
    username = chat.to_user.username
    chat.delete()
    messages.add_message(request, messages.INFO, "Your message deleted succesfully.")
    return HttpResponseRedirect(reverse("inbox:message_user", args=(username, )))

inbox/templates/index.html
<div id="container">
	<aside>
		<header>
			<input type="text" placeholder="search">
		</header>
		<ul>
			<li>
				<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/chat_avatar_01.jpg" alt="">
				<div>
					<h2>Prénom Nom</h2>
					<h3>
						<span class="status orange"></span>
						offline
					</h3>
				</div>
			</li>
			<li>
				<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/chat_avatar_02.jpg" alt="">
				<div>
					<h2>Prénom Nom</h2>
					<h3>
						<span class="status green"></span>
						online
					</h3>
				</div>
			</li>
			<li>
				<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/chat_avatar_03.jpg" alt="">
				<div>
					<h2>Prénom Nom</h2>
					<h3>
						<span class="status orange"></span>
						offline
					</h3>
				</div>
			</li>
			<li>
				<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/chat_avatar_04.jpg" alt="">
				<div>
					<h2>Prénom Nom</h2>
					<h3>
						<span class="status green"></span>
						online
					</h3>
				</div>
			</li>
			<li>
				<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/chat_avatar_05.jpg" alt="">
				<div>
					<h2>Prénom Nom</h2>
					<h3>
						<span class="status orange"></span>
						offline
					</h3>
				</div>
			</li>
			<li>
				<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/chat_avatar_06.jpg" alt="">
				<div>
					<h2>Prénom Nom</h2>
					<h3>
						<span class="status green"></span>
						online
					</h3>
				</div>
			</li>
			<li>
				<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/chat_avatar_07.jpg" alt="">
				<div>
					<h2>Prénom Nom</h2>
					<h3>
						<span class="status green"></span>
						online
					</h3>
				</div>
			</li>
			<li>
				<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/chat_avatar_08.jpg" alt="">
				<div>
					<h2>Prénom Nom</h2>
					<h3>
						<span class="status green"></span>
						online
					</h3>
				</div>
			</li>
			<li>
				<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/chat_avatar_09.jpg" alt="">
				<div>
					<h2>Prénom Nom</h2>
					<h3>
						<span class="status green"></span>
						online
					</h3>
				</div>
			</li>
			<li>
				<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/chat_avatar_10.jpg" alt="">
				<div>
					<h2>Prénom Nom</h2>
					<h3>
						<span class="status orange"></span>
						offline
					</h3>
				</div>
			</li>
		</ul>
	</aside>
	<main>
		<header>
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/chat_avatar_01.jpg" alt="">
			<div>
				<h2>Chat with Vincent Porter</h2>
				<h3>already 1902 messages</h3>
			</div>
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/ico_star.png" alt="">
		</header>
		<ul id="chat">
			<li class="you">
				<div class="entete">
					<span class="status green"></span>
					<h2>Vincent</h2>
					<h3>10:12AM, Today</h3>
				</div>
				<div class="triangle"></div>
				<div class="message">
					Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
				</div>
			</li>
			<li class="me">
				<div class="entete">
					<h3>10:12AM, Today</h3>
					<h2>Vincent</h2>
					<span class="status blue"></span>
				</div>
				<div class="triangle"></div>
				<div class="message">
					Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
				</div>
			</li>
			<li class="me">
				<div class="entete">
					<h3>10:12AM, Today</h3>
					<h2>Vincent</h2>
					<span class="status blue"></span>
				</div>
				<div class="triangle"></div>
				<div class="message">
					OK
				</div>
			</li>
			<li class="you">
				<div class="entete">
					<span class="status green"></span>
					<h2>Vincent</h2>
					<h3>10:12AM, Today</h3>
				</div>
				<div class="triangle"></div>
				<div class="message">
					Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
				</div>
			</li>
			<li class="me">
				<div class="entete">
					<h3>10:12AM, Today</h3>
					<h2>Vincent</h2>
					<span class="status blue"></span>
				</div>
				<div class="triangle"></div>
				<div class="message">
					Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
				</div>
			</li>
			<li class="me">
				<div class="entete">
					<h3>10:12AM, Today</h3>
					<h2>Vincent</h2>
					<span class="status blue"></span>
				</div>
				<div class="triangle"></div>
				<div class="message">
					OK
				</div>
			</li>
		</ul>
		<footer>
			<textarea placeholder="Type your message"></textarea>
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/ico_picture.png" alt="">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/1940306/ico_file.png" alt="">
			<a href="#">Send</a>
		</footer>
	</main>
</div>

inbox/templates/message.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'chat/style.css' %}" type="text/css" />
<div id="container" >
	<aside>
		<header>
			<input type="text" placeholder="search">
		</header>
       
		<ul>
            {% for user in users %}
			<li>
                {% if user.profile.avatar %}
                    <img class="chatimage" src="{{ user.profile.avatar.url }}" alt="text"/>
                {% endif %}               
				<div>
					 <a class="{% if user.username != username %}text-decoration-none{% endif %}" href="{% url 'inbox:message_user' user.username %}">
                        {{ user.first_name }}
                    </a>
					<h3>
						<span class="status green"></span>
					</h3>
				</div>
			</li>
            {% endfor %}
		</ul>
	</aside>
	<main>
		<header>
		{% if to_user.profile.avatar.url %}
		<img class="chatimage" src="{{ to_user.profile.avatar.url }}" alt="text"/>
		{% endif %}
			<div>
				<h2>{{ to_user.first_name }}</h2>
			</div>
			</header>
			
			
			<ul id="chat">
			{% for chat in conversations %}
			{% if chat.from_user != request.user %}
			<li class="you">
				<div class="entete">
					<span class="status green"></span>
					<h2>{{ chat.created_at }}</h2>
					<h3>{{ chat.from_user.first_name }}</h3>
				</div>
				<div class="triangle"></div>
				<div class="message">
					{{ chat.description }}
				</div>
			</li>
			{% endif %}
			{% if chat.from_user == request.user %}
			<li class="me">
				<div class="entete">
					<h3>{{ chat.created_at }}</h3>
					<h2>{{ chat.from_user.first_name }}</h2>
					<span class="status blue"></span>
				</div>
				<div class="triangle"></div>
				<div class="message" >
                    {{ chat.description }}
					{% if chat.from_user == request.user %}
				<a class="text-decoration-none text-danger" href="#" data-messageid="{{chat.id}}" data-bs-toggle="modal" data-bs-target="#exampleModal">
					<small class="small">
						Delete
					</small>
				</a>
            {% endif %}
				</div>
				{% if messages %}
					{% for message in messages %}
						<div class="alert alert-success">
							{{ message }}
						</div>
					{% endfor %}
				{% endif %}
			</li>
			{% endif %}
            {% endfor %}
			
		</ul>
		<footer>
            <form method="post" action="">{% csrf_token %}
			<textarea type = "text" placeholder="Type your message" name="description"></textarea>
			<input class="btn btn-secondary" type="submit" name="submit" value="Send" />
            </form>
		</footer>
	</main>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Message</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this message ?
          <form id="del-form" method="post" action="{% url 'inbox:delete_message' %}">
              {% csrf_token %}
              <input id="_messageid" type="hidden" name="messageid" />
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button id="del-btn" type="button" class="btn btn-danger">Yes</button>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}
{% block script %}
  {{ block.super }}
  <script type="text/javascript">
      $(document).ready(function(){
          let modal = document.getElementById("exampleModal");
          modal.addEventListener("show.bs.modal", function(evt){
              let deleteButton = evt.relatedTarget;
              $("#_messageid").val(deleteButton.dataset.messageid);
          });
          $("#del-btn").click(function(){
              $("#del-form").submit();
          })
      });
  
  </script>
  
  {% endblock script %}