bihe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("story.urls", namespace="story")),
    path("user/", include("useraccount.urls", namespace="user")),
    path("inbox/", include("inbox.urls", namespace="inbox")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inbox/urls.py
from django.urls import path
from inbox.views import message_view, message_to_user, delete_message
app_name="inbox"

urlpatterns = [
    path("messages/", message_view, name="messages"),
    path("messages/<str:username>/", message_to_user, name="message_user"),
    path("delete-message/", delete_message, name="delete_message"),
]

story/urls.py
from django.urls import path
from story.views import home, dash, matches

app_name = "story"

urlpatterns = [
    path("", home, name="home"),
    path("dash/", dash, name="dash"),
    path("matches/", matches, name="matches"),
]

useraccount/urls.py
from django.urls import path
from useraccount.views import user_login, user_logout, SignupView, profile_view, edit_profile_view, visit_profile, PassWordChange, search

app_name = "user"

urlpatterns = [
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("registration/", SignupView.as_view(), name="registration"),
    path("profile/<str:username>/", profile_view, name="profile"),
    path("visit-profile/<int:profileid>/", visit_profile, name="visit_profile"),
    path("edit_profile/<str:username>/", edit_profile_view, name="edit_profile"),
    path("password",PassWordChange.as_view(template_name="password_change_form.html"),name="password-change"),
    path("search/", search, name="search"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <title>BIHE</title>
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock navbar %}


    {% block stylesheet %}
        <link rel = "stylesheet" href="{% static 'css/bs.min.css' %}" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'navbar/fonts/icomoon/style.css' %}" />

        <link rel="stylesheet" href="{% static 'navbar/css/owl.carousel.min.css' %}" />

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'navbar/css/bootstrap.min.css' %}" />
        
        <!-- Style -->
        <link rel="stylesheet" href="{% static 'navbar/css/style.css' %}" />
        <link rel="stylesheet" href="{% static 'css/nav.css' %}" />
        <link  rel="stylesheet" href="{% static 'profile/bs2.min.css' %}" />
        <link  rel="stylesheet" href="{% static '/profile/button.css' %}" />
    {% endblock stylesheet %}
</head>
    <div class="">
        
        {% block content %}

        {% endblock content %}

    </div>

    {% block script %}
    <script src="{% static 'js/jquery.min.js' %}" type = "text/javascript"></script>
    <script src="{% static 'js/bs.min.js' %}" type = "text/javascript"></script>
    <script src="{% static 'navbar/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'navbar/js/popper.min.js' %}" ></script>
    <script src="{% static 'navbar/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'navbar/js/jquery.sticky.js' %}"></script>
    <script src="{% static 'navbar/js/main.js' %}"></script>
    <script src="{% static 'css/nav.css' %}"></script>
    {% endblock script %}

</body>
</html>

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>BIHE</title>
<style>
body {
	background: #eeeeee;
}
.form-inline {
	display: inline-block;
}
.navbar-header.col {
	padding: 0 !important;
}
.navbar {		
	background: #fff;
	padding-left: 16px;
	padding-right: 16px;
	border-bottom: 1px solid #d6d6d6;
	box-shadow: 0 0 4px rgba(0,0,0,.1);
}
.nav-link img {
	border-radius: 50%;
	width: 36px;
	height: 36px;
	margin: -8px 0;
	float: left;
	margin-right: 10px;
}
.navbar .navbar-brand {
	color: #555;
	padding-left: 0;
	padding-right: 50px;
	font-family: 'Merienda One', sans-serif;
}
.navbar .navbar-brand i {
	font-size: 20px;
	margin-right: 5px;
}
.search-box {
	position: relative;
}	
.search-box input {
	box-shadow: none;
	padding-right: 35px;
	border-radius: 3px !important;
}
.search-box .input-group-addon {
	min-width: 35px;
	border: none;
	background: transparent;
	position: absolute;
	right: 0;
	z-index: 9;
	padding: 7px;
	height: 100%;
}
.search-box i {
	color: #a0a5b1;
	font-size: 19px;
}
.navbar .nav-item i {
	font-size: 18px;
}
.navbar .dropdown-item i {
	font-size: 16px;
	min-width: 22px;
}
.navbar .nav-item.open > a {
	background: none !important;
}
.navbar .dropdown-menu {
	border-radius: 1px;
	border-color: #e5e5e5;
	box-shadow: 0 2px 8px rgba(0,0,0,.05);
}
.navbar .dropdown-menu a {
	color: #777;
	padding: 8px 20px;
	line-height: normal;
}
.navbar .dropdown-menu a:hover, .navbar .dropdown-menu a:active {
	color: #333;
}	
.navbar .dropdown-item .material-icons {
	font-size: 21px;
	line-height: 16px;
	vertical-align: middle;
	margin-top: -2px;
}
.navbar .badge {
	color: #fff;
	background: #f44336;
	font-size: 11px;
	border-radius: 20px;
	position: absolute;
	min-width: 10px;
	padding: 4px 6px 0;
	min-height: 18px;
	top: 5px;
}
.navbar a.notifications, .navbar a.messages {
	position: relative;
	margin-right: 10px;
}
.navbar a.messages {
	margin-right: 20px;
}
.navbar a.notifications .badge {
	margin-left: -8px;
}
.navbar a.messages .badge {
	margin-left: -4px;
}	
.navbar .active a, .navbar .active a:hover, .navbar .active a:focus {
	background: transparent !important;
}
@media (min-width: 1200px){
	.form-inline .input-group {
		width: 300px;
		margin-left: 30px;
	}
}
@media (max-width: 1199px){
	.form-inline {
		display: block;
		margin-bottom: 10px;
	}
	.input-group {
		width: 100%;
	}
}
</style>
</head> 
<body>
<nav class="navbar navbar-expand-xl navbar-light bg-light">
	<a href="" class="navbar-brand"><i class="fa fa-cube"></i>Bihe<b>.com</b></a>
	<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
		<span class="navbar-toggler-icon"></span>
	</button>
	<!-- Collection of nav links, forms, and other content for toggling -->
	<div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
		<div class="navbar-nav">
			<a href="{% url 'story:dash' %}" class="nav-item nav-link active">Dashboard</a>
			<div class="nav-item dropdown">
				<a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">Matches</a>
				<div class="dropdown-menu">
					<a href="{% url 'story:matches' %}" class="dropdown-item">My Matches</a>
				</div>
			</div>
			<a href="{% url 'inbox:messages' %}" class="nav-item nav-link">Inbox</a>
		</div>
		<form method="get" action="{% url 'user:search' %}" class="navbar-form form-inline">
			<div class="input-group search-box">								
				<input type="search" class="form-control" placeholder="Search by Name" name="search" id="search">
				<button class="input-group-addon" type="submit"></button>
			</div>
		</form>
		{% if request.user.is_authenticated %}
		<div class="navbar-nav ml-auto">
			<a href="#" class="nav-item nav-link notifications"><i class="fa fa-bell-o"></i><span class="badge"></span></a>
			<a href="#" class="nav-item nav-link messages"><i class="fa fa-envelope-o"></i><span class="badge"></span></a></a>
			<div class="nav-item dropdown">
				<a data-toggle="dropdown" class="nav-link dropdown-toggle user-action">
				<style>
					.thumb {
						width: 30px;
						height: 30px;
						border: none;
						border-radius: 15px;
					}                        
                </style>
                        {% if user.profile.avatar %}
                            <img class="thumb" src="{{ user.profile.avatar.url }}" alt=""/>
                        {% endif %}
				<b class="caret">{{ request.user.first_name}} {{ request.user.last_name }}</b></a>
				<div class="dropdown-menu">
				
					<a href="{% url 'user:profile' request.user.username %}" class="dropdown-item"><i class="fa fa-user-o"></i> Profile</a></a>
					<a href="{% url 'user:password-change' %}" class="dropdown-item"><i class="fa fa-sliders"></i> Change Password</a></a>
					<div class="dropdown-divider"></div>
					<a href="{% url 'user:logout' %}" class="dropdown-item"><i class="material-icons">&#xE8AC;</i> Logout</a></a>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</nav>
</body>
</html>                            